steps:

  - block: ":rubygems: Release? :thumbsup: / :thumbsdown:"
    prompt: "One day, we'll release all the time, like good devops. Until then, we'll give ourselves an option."
    fields:
      - select: "Do you want to release this to Rubygems?"
        key: "rubygems-release-confirmation"
        options:
          - label: "Yup, release it!"
            value: "yes"
          - label: "Nope, not just now"
            value: "no"

  - label: ":thinking_face:"
    command: .buildkite/scripts/maybe_release.sh
